version: "3.9"

services:
  zkbob-redis:
    command: [redis-server, --appendonly, 'yes']
    image: redis:6.2.6
    volumes: ['~/redis:/data']
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  zkbob-relayer:
    image: ghcr.io/zkbob/zkbob-relayer:${RELAYER_IMAGE:-latest}
    restart: always
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f --connect-timeout 1 --max-time 2 --retry 2 --retry-delay 3 --retry-max-time 15 http://127.0.0.1:80/info || sh -c 'pkill -15 -f \"/usr/local/bin/node index.js\" && (sleep 10; pkill -9 -f \"/usr/local/bin/node index.js\")'"]
      interval: 60s
      timeout: 30s
      start_period: 30s
    depends_on:
      - zkbob-redis
    env_file: .env
    environment:
      - PORT=80
      - RELAYER_REDIS_URL=zkbob-redis:6379
      - TX_PROOFS_DIR=./tx_proofs
    volumes:
      - ./params:/app/zp-relayer/params
      - relayer_optimistic_tree:/app/zp-relayer/optimisticTree.db
      - relayer_optimistic_txs:/app/zp-relayer/optimisticTxs.db
      - relayer_tree:/app/zp-relayer/poolTree.db
      - relayer_txs:/app/zp-relayer/poolTxs.db
    ports:
      - $PUB_PORT:80
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }

volumes:
  relayer_optimistic_tree:
  relayer_optimistic_txs:
  relayer_tree:
  relayer_txs: