version: "3.9"

services:
  zkbob-redis:
    command: [redis-server, --appendonly, 'yes']
    image: redis:6.2.6
    volumes: ['./redis:/data']
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  zkbob-relayer:
    image: ghcr.io/zkbob/zkbob-relayer:${RELAYER_IMAGE:-latest}
    restart: unless-stopped
    container_name: zkbob-relayer
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -f --connect-timeout 1 --max-time 2 --retry 2 --retry-delay 3 --retry-max-time 15 http://127.0.0.1:80/info || sh -c 'pkill -15 -f \"/usr/local/bin/node index.js\" && (sleep 10; pkill -9 -f \"/usr/local/bin/node index.js\")'"]
      interval: 60s
      timeout: 30s
      start_period: 30s
    depends_on:
      - zkbob-redis
    env_file: .env
    environment:
      - PORT=80
      - RELAYER_REDIS_URL=zkbob-redis:6379
      - STATE_DIR_PATH=state_db
    volumes:
      - ./params:/app/zp-relayer/params
      - ./state_db:/app/zp-relayer/state_db
    ports:
      - $PUB_PORT:80
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
